import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import path from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";
import { readFileSync } from "node:fs";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../../..");
const operator="11111111-1111-1111-1111-111111111111";
function sql(statement){return execFileSync("docker",["exec","-i","n8n-pgvector","sh","-lc","exec psql -X -q -v ON_ERROR_STOP=1 -U \"$POSTGRES_USER\" -d zh_narrative_test -At -f -"],{cwd:root,input:statement,encoding:"utf8"}).trim()}
function rpc(input){return JSON.parse(sql(`SELECT public.rpc_workbench($$${JSON.stringify(input)}$$::jsonb)::text;`))}
function items(overrides={}){const values={prompt:{text:"Test prompt"},model:{provider:"openai",model:"gpt-test",connection_tested:true},budget:{max_tokens:512},automation:{production:false,audit:false,iteration:false},presentation:{emotion:.5,pacing:.5},...overrides};return Object.entries(values).map(([kind,effective_value])=>({kind,scope:"operator",effective_value}))}
test("workbench installer runs through stdin and creates the closed projection",()=>{const installer=path.join(root,"db/functions/workbench/install-workbench.mjs");execFileSync(process.execPath,[installer],{cwd:root,env:{...process.env,ZH_WORKBENCH_DATABASE:"zh_narrative_test"},stdio:"inherit"});assert.equal(sql("SELECT to_regclass('public.t_workbench_config_versions') IS NOT NULL;"),"t");assert.equal(sql("SELECT EXISTS (SELECT 1 FROM pg_proc WHERE proname='rpc_workbench' AND oidvectortypes(proargtypes)='jsonb');"),"t");const empty=rpc({action:"load",local_operator_id:operator});assert.equal(empty.ok,true);assert.equal(empty.config.length,5);assert.equal(JSON.stringify(empty).includes("api_key"),false);});
test("five-item save is atomic, versions, and FP001-03 projection sync",()=>{const before=Number(sql(`SELECT count(*) FROM public.t_workbench_config_versions WHERE local_operator_id='${operator}';`));const bad=rpc({action:"save",local_operator_id:operator,items:items({budget:{max_tokens:0}})});assert.equal(bad.ok,false);assert.equal(Number(sql(`SELECT count(*) FROM public.t_workbench_config_versions WHERE local_operator_id='${operator}';`)),before);const saved=rpc({action:"save",local_operator_id:operator,items:items()});assert.equal(saved.ok,true);assert.equal(Number(sql(`SELECT count(*) FROM public.t_workbench_config_versions WHERE local_operator_id='${operator}' AND status='active';`)),5);assert.equal(sql("SELECT model_name || ':' || max_tokens FROM public.t_prompt_configs WHERE node_code='FP001-03' AND status='active' ORDER BY updated_at DESC LIMIT 1;"),"gpt-test:512");const next=rpc({action:"save",local_operator_id:operator,items:items({automation:{production:true,audit:false,iteration:false}})});assert.equal(next.error.code,"AUTOMATION_NOT_READY");const connection=rpc({action:"save",local_operator_id:operator,items:items({model:{provider:"openai",model:"gpt-test",connection_tested:false}})});assert.equal(connection.error.code,"CONNECTION_TEST_REQUIRED");});
test("ZH00 canonical keeps the credential test response closed and inspectable",()=>{const file=path.join(root,"docs","后端","n8n","ZH00-统一配置.json");const workflow=JSON.parse(readFileSync(file,"utf8"));assert.equal(workflow.name,"ZH00-统一配置");const webhooks=workflow.nodes.filter((node)=>node.type==="n8n-nodes-base.webhook");assert.deepEqual(webhooks.map((node)=>node.parameters.path),["workbench"]);const credential=workflow.nodes.find((node)=>node.name==="Test OpenAI credential");assert.equal(credential.parameters.options.response.response.fullResponse,true);assert.equal(credential.parameters.options.response.response.neverError,true);assert.equal(credential.onError,"continueRegularOutput");const normalizer=workflow.nodes.find((node)=>node.name==="Redact credential test result").parameters.jsCode;assert.match(normalizer,/\$json\.statusCode/);assert.match(normalizer,/connection_tested:true/);assert.doesNotMatch(JSON.stringify(workflow),/api_key|password|secret/i);});
test("workbench hidden overlays are absent until their state machine opens them",()=>{const html=readFileSync(path.join(root,"apps","web","src","pages","workbench","index.html"),"utf8");const source=readFileSync(path.join(root,"apps","web","src","pages","workbench","workbench.mjs"),"utf8");assert.match(source,/\[hidden\]\{display:none!important\}/);for(const id of ["modelSettingsModal","stageUnavailable","bookMenu","popover"])assert.match(html,new RegExp(`id=\\"${id}\\"[^>]*hidden|hidden[^>]*id=\\"${id}\\"`));for(const klass of ["node n1","node n6","node n4","node n5"])assert.match(html,new RegExp(`class=\\"${klass}\\"`));});
