import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

test("skill library uses the V7 management contract and keeps built-ins read-only", async () => {
  const [routes, server, page, sidebar] = await Promise.all([
    readFile(new URL("../src/app/routes.mjs", import.meta.url), "utf8"),
    readFile(new URL("../src/app/server.mjs", import.meta.url), "utf8"),
    readFile(new URL("../src/pages/skill-library/index.html", import.meta.url), "utf8"),
    readFile(new URL("../src/pages/prototype/common/sidebar.js", import.meta.url), "utf8"),
  ]);

  assert.match(routes, /skill_library\\\.html/);
  assert.match(routes, /pages\/skill-library\/index\.html/);
  assert.match(server, /pathname === "\/api\/skill-library"/);
  assert.match(server, /rpc_get_effective_skills/);
  assert.match(server, /rpc_manage_skill/);
  assert.match(server, /"import_overwrite"/);
  assert.match(page, /current_book_context/);
  assert.match(page, /const result = await request\(\{ action: 'operator' \}\);/);
  assert.match(page, /const storedBookBelongsToOperator = Boolean\(/);
  assert.match(page, /stored\.local_operator_id\.toLowerCase\(\) === operatorId\.toLowerCase\(\)/);
  assert.match(page, /if \(!storedBookBelongsToOperator\) \{/);
  assert.doesNotMatch(page, /localStorage\.getItem\('zhreplan\.local_operator_id\.v1'\)/);
  assert.match(page, /const skillErrorMessages = \{/);
  assert.match(page, /BUILTIN_READ_ONLY:/);
  assert.match(page, /RPC_UNAVAILABLE:/);
  assert.match(page, /SKILL_IMPORT_INCOMPLETE:/);
  assert.match(page, /skillErrorMessages\[code\] \|\| rpcError\.message/);
  assert.match(page, /系统内置技能只读/);
  assert.match(page, /技能评价流程尚未启用/);
  assert.doesNotMatch(page, /defaultSkillData/);
  assert.match(page, /window\.skillData = \{\};/);
  assert.doesNotMatch(page, /localStorage\.setItem\('skillData'/);
  assert.match(page, /preferenceStatus: null,/);
  assert.match(page, /drawerMetadata\('所有者', owner\)/);
  assert.doesNotMatch(page, /function hasBookContext/);
  assert.doesNotMatch(page, /function preferenceCheckbox/);
  assert.doesNotMatch(page, /set_preference/);
  assert.doesNotMatch(page, /data-preference-id/);
  assert.doesNotMatch(page, /本书偏好/);
  assert.doesNotMatch(page, /\n\s*SCOPE_REJECTED:/);
  assert.match(page, /read_mode: 'management'/);
  assert.match(page, /ownerLocalOperatorId/);
  assert.match(page, /lifecycleStatus/);
  assert.match(page, /action: 'import_overwrite'/);
  assert.match(page, /skills: rows/);
  assert.match(page, /const importColumns = \[/);
  assert.match(page, /const csvColumns = \[\.\.\.importColumns, 'null_fields'\]/);
  assert.match(page, /payload\[column\] = null/);
  assert.match(page, /function parseCsv\(text\)/);
  assert.match(page, /narrative_user_managed_skills\.csv/);
  assert.match(page, /pagination-controls/);
  assert.match(page, /\[10, 20, 50\]/);
  assert.match(page, /data-shared-sidebar/);
  assert.match(page, /prototype\/common\/sidebar\.js/);
  assert.doesNotMatch(page, /notifications:\s*['"]/);
  assert.doesNotMatch(page, /window\.toggleSidebar\s*=/);
  assert.match(page, /id="drawerEditableActions"/);
  assert.match(page, /id="drawerSaveBtn"[^>]*onclick="saveDrawerSkill\(\)"/);
  assert.match(page, /id="drawerAiAnalysisBtn"[^>]*disabled/);
  assert.match(page, /function buildSkillPayload\(category, existing, value\)/);
  assert.match(page, /function drawerPayload\(item\)/);
  assert.match(page, /window\.saveDrawerSkill = async function\(\)/);
  assert.match(page, /const canManage = item\.sourceType === 'user_managed' && item\.lifecycleStatus === 'active' && Boolean\(item\.stableSlug\);/);
  assert.match(page, /deleteButton\.hidden = !canManage;/);
  assert.match(page, /editableActions\.classList\.toggle\('hidden', !canManage\);/);
  assert.match(page, /analysisButton\.disabled = true;/);
  assert.match(page, /if \(mode !== 'add'\) return showToast\('用户管理技能请在详情页直接编辑。'\);/);
  assert.doesNotMatch(page, /drawerEditBtn/);
  assert.doesNotMatch(page, /openSkillFormModal\('edit'/);
  assert.doesNotMatch(page, /onclick="triggerAIAnalysis\(\)"/);
  assert.match(sidebar, /window\.mountSharedSidebar = mountSharedSidebar/);
  assert.match(sidebar, /precision_manufacturing/);
  assert.match(sidebar, /sidebar-separator/);
  assert.doesNotMatch(page, /managementWritesAvailable/);
  assert.doesNotMatch(page, /atomicManagementContractHint/);
  assert.doesNotMatch(page, /skill-import-preference/);
  assert.doesNotMatch(page, /已保存并绑定到当前作品/);
  assert.doesNotMatch(page, /return renderStatus\('当前未选择作品，请先从总控面板进入一个作品。'\)/);
  assert.match(page, /function refreshActiveDrawer\(\) \{/);
  assert.match(page, /const refreshedItem = state\.skills\.find\(candidate => activeItem\.stableSlug/);
  assert.match(page, /candidate\.stableSlug === activeItem\.stableSlug/);
  assert.match(page, /candidate\.id === activeItem\.id/);
  assert.match(page, /window\.openDrawer\(refreshedItem\);/);

  const submitStart = page.lastIndexOf("window.submitSkillForm");
  const deleteStart = page.lastIndexOf("window.deleteSkill");
  const importStart = page.lastIndexOf("window.importSkills");
  const patchStart = page.lastIndexOf("function patchPrototypeControls");
  const navigationStart = page.lastIndexOf("function syncNavigation");
  const loadStart = page.lastIndexOf("async function loadSkills");
  const payloadStart = page.lastIndexOf("function buildSkillPayload");
  const drawerPayloadStart = page.lastIndexOf("function drawerPayload");
  const drawerSaveStart = page.lastIndexOf("window.saveDrawerSkill");
  const submitBlock = page.slice(submitStart, page.indexOf("const importColumns", submitStart));
  const deleteBlock = page.slice(deleteStart, page.indexOf("function formPayload", deleteStart));
  const importBlock = page.slice(importStart, page.indexOf("function patchPrototypeControls", importStart));
  const patchBlock = page.slice(patchStart, navigationStart);
  const navigationBlock = page.slice(navigationStart, loadStart);
  const loadBlock = page.slice(loadStart, page.indexOf("window.addEventListener", loadStart));
  const payloadBlock = page.slice(payloadStart, drawerPayloadStart);
  const drawerPayloadBlock = page.slice(drawerPayloadStart, drawerSaveStart);
  const drawerSaveBlock = page.slice(drawerSaveStart, page.indexOf("window.submitSkillForm", drawerSaveStart));
  assert.doesNotMatch(submitBlock, /set_preference/);
  assert.doesNotMatch(importBlock, /create_version/);
  assert.doesNotMatch(submitBlock, /book_id:/);
  assert.doesNotMatch(deleteBlock, /book_id:/);
  assert.doesNotMatch(importBlock, /book_id:/);
  assert.doesNotMatch(patchBlock, /请先选择作品/);
  assert.doesNotMatch(navigationBlock, /disabled = !bookId/);
  assert.match(navigationBlock, /function syncManagementControls\(\)/);
  assert.match(navigationBlock, /state\.loading \|\| state\.busy \|\| Boolean\(state\.error\)/);
  assert.match(navigationBlock, /button\.disabled = blocked/);
  assert.match(navigationBlock, /const bookId = state\.context\?\.current_book_id;/);
  assert.match(loadBlock, /name\.textContent = '全局技能库';/);
  assert.match(loadBlock, /const result = await request\(\{ action: 'list', read_mode: 'management', local_operator_id: state\.context\.local_operator_id \}, \{ signal: controller\?\.signal \}\);/);
  assert.match(loadBlock, /controller\.abort\(\), 12000/);
  assert.match(loadBlock, /技能数据服务响应超时/);
  assert.doesNotMatch(loadBlock, /book_id:/);
  assert.doesNotMatch(loadBlock, /SCOPE_REJECTED/);
  assert.doesNotMatch(loadBlock, /discardInvalidBookContext/);
  assert.match(loadBlock, /renderGrid\(\);\s*refreshActiveDrawer\(\);/);
  assert.match(payloadBlock, /action: 'create_version'/);
  assert.match(drawerPayloadBlock, /return buildSkillPayload\(item\.category, item,/);
  assert.match(drawerSaveBlock, /const body = drawerPayload\(item\);/);
  assert.match(drawerSaveBlock, /await request\(body\);/);
  assert.match(drawerSaveBlock, /技能新版本已保存/);
});
