const endpoint="/webhook/workbench", operatorKey="zhreplan.local_operator_id.v1", contextKey="current_book_context", $=(s)=>document.querySelector(s);
const state={operator:"",bookId:null,books:[],config:[],tested:false};
function stableOperator(){const value=localStorage.getItem(operatorKey);if(value)return value;const next=crypto.randomUUID();localStorage.setItem(operatorKey,next);return next}
function show(kind,text){const box=$("#runtime");box.className=`runtime ${kind}`;box.textContent=text}
async function call(payload){const response=await fetch(endpoint,{method:"POST",headers:{"content-type":"application/json",accept:"application/json"},body:JSON.stringify(payload)});const result=await response.json().catch(()=>({}));if(!response.ok||!result.ok)throw new Error(result?.error?.message||"Configuration service is unavailable.");return result}
const projected=(kind,fallback={})=>state.config.find((item)=>item.kind===kind)?.effective_value||fallback;
function syncSave(){const save=$("#save");save.disabled=!state.tested;save.setAttribute("aria-disabled",String(!state.tested));save.title=state.tested?"保存为新版本":"请先成功测试当前模型连接"}
function renderBooks(){const target=$("#bookList"),query=$("#bookSearch").value.trim().toLowerCase();target.replaceChildren();for(const book of state.books.filter((row)=>!query||row.title.toLowerCase().includes(query))){const button=document.createElement("button");button.className="book-option";button.textContent=`${book.title} · ${book.stage||"design"}`;button.onclick=()=>{localStorage.setItem(contextKey,JSON.stringify({local_operator_id:state.operator,current_book_id:book.book_id}));state.bookId=book.book_id;$("#bookMenu").hidden=true;load()};target.append(button)}if(!target.children.length)target.textContent="没有匹配的本地作品。"}
function render(){const book=state.books.find((row)=>row.book_id===state.bookId),prompt=projected("prompt"),model=projected("model"),budget=projected("budget"),automation=projected("automation",{production:false,audit:false,iteration:false}),presentation=projected("presentation",{emotion:.5,pacing:.5});state.tested=model.connection_tested===true;$("#headerBook").textContent=book?.title||"未选择作品";$("#bookSelect").replaceChildren(document.createTextNode(book?.title||"选择作品"),Object.assign(document.createElement("span"),{textContent:"⌄"}));$("#bookGenre").textContent=book?.genre||"本地作品";$("#bookStage").textContent=book?.stage||"-";$("#prompt").value=prompt.text||"";$("#provider").value=model.provider||"openai";$("#model").value=model.model||"";$("#modelSummary").textContent=model.model||"未配置";$("#budget").value=budget.max_tokens||"";$("#budgetSummary").textContent=budget.max_tokens?`${budget.max_tokens} tokens`:"未配置";$("#emotion").value=presentation.emotion??.5;$("#pacing").value=presentation.pacing??.5;document.querySelectorAll("[data-auto]").forEach((input)=>input.checked=Boolean(automation[input.dataset.auto]));const versions=state.config.map((item)=>item.version).filter(Boolean);$("#version").textContent=versions.length?`有效版本 v${Math.max(...versions)}`:"尚无 active 版本";renderBooks();syncSave()}
async function load(){show("loading","正在读取 PostgreSQL 有效配置投影…");try{const data=await call({action:"load",local_operator_id:state.operator,book_id:state.bookId});state.books=data.books||[];if(state.bookId&&!state.books.some((b)=>b.book_id===state.bookId))state.bookId=null;if(!state.bookId&&state.books.length)state.bookId=state.books[0].book_id;state.config=data.config||[];render();show(data.state==="empty"?"empty":"ready",data.state==="empty"?"暂无作品。请先在新书页创建作品。":"已读取当前本地操作者的有效配置。")}catch(error){show("failure",error.message)}}
function command(){const scope=state.bookId?"book":"operator";return[{kind:"prompt",scope,effective_value:{text:$("#prompt").value.trim()}},{kind:"model",scope,effective_value:{provider:$("#provider").value.trim(),model:$("#model").value.trim(),connection_tested:state.tested}},{kind:"budget",scope,effective_value:{max_tokens:Number($("#budget").value)}},{kind:"automation",scope,effective_value:Object.fromEntries([...document.querySelectorAll("[data-auto]")].map((i)=>[i.dataset.auto,i.checked]))},{kind:"presentation",scope,effective_value:{emotion:Number($("#emotion").value),pacing:Number($("#pacing").value)}}]}
$("#configForm").addEventListener("submit",async(event)=>{event.preventDefault();show("loading","正在保存新的 active 配置版本…");try{await call({action:"save",local_operator_id:state.operator,book_id:state.bookId,items:command()});state.tested=false;$("#connectionState").textContent="模型偏好已保存；页面从未持有或传输密钥。";await load();show("ready","保存完成，已回显新的 active 配置版本。")}catch(error){show("failure",error.message)}});
$("#testConnection").onclick=async()=>{$("#connectionState").textContent="正在使用 n8n 已配置凭据测试连接…";try{const result=await call({action:"test_connection",local_operator_id:state.operator});state.tested=result.connection_tested===true;syncSave();$("#connectionState").textContent=state.tested?"连接测试成功；现在可以保存模型偏好。":"连接测试失败；保存仍被阻断。"}catch(error){state.tested=false;syncSave();$("#connectionState").textContent=`连接失败：${error.message}`}};
$("#cancel").onclick=()=>{state.tested=false;render();show("ready","已恢复后端有效配置。")};$("#refresh").onclick=load;$("#bookSelect").onclick=()=>{const menu=$("#bookMenu");menu.hidden=!menu.hidden;$("#bookSelect").setAttribute("aria-expanded",String(!menu.hidden));renderBooks()};$("#bookSearch").oninput=renderBooks;$("#settings").onclick=()=>$("#popover").hidden=!$("#popover").hidden;$("#sidebarToggle").onclick=()=>document.body.classList.toggle("collapsed");
$("#provider").addEventListener("input",()=>{state.tested=false;syncSave()});$("#model").addEventListener("input",()=>{state.tested=false;syncSave()});syncSave();
document.querySelectorAll(".node").forEach((node)=>node.addEventListener("click",()=>{document.querySelectorAll(".node").forEach((n)=>n.classList.remove("selected"));node.classList.add("selected");$("#nodeTitle").textContent=node.dataset.node;$("#nodeHint").textContent="该节点将冻结当前有效配置版本。"}));
const viewport=$("#canvasViewport"),content=$("#canvasContent");let x=0,y=0,scale=1,drag=null;function paint(){content.style.transform=`translate(${x}px,${y}px) scale(${scale})`;$("#zoom").value=`${Math.round(scale*100)}%`}function zoom(delta){scale=Math.max(.7,Math.min(1.3,scale+delta));paint()}$("#zoomIn").onclick=()=>zoom(.1);$("#zoomOut").onclick=()=>zoom(-.1);viewport.addEventListener("pointerdown",(event)=>{if(event.target.closest(".node,button,select"))return;drag={x:event.clientX,y:event.clientY,ox:x,oy:y};viewport.setPointerCapture(event.pointerId);viewport.classList.add("dragging")});viewport.addEventListener("pointermove",(event)=>{if(!drag)return;x=drag.ox+event.clientX-drag.x;y=drag.oy+event.clientY-drag.y;paint()});viewport.addEventListener("pointerup",()=>{drag=null;viewport.classList.remove("dragging")});viewport.addEventListener("keydown",(event)=>{if(event.key==="+"||event.key==="=")zoom(.1);if(event.key==="-")zoom(-.1);if(event.key==="ArrowLeft")x-=20;if(event.key==="ArrowRight")x+=20;if(event.key==="ArrowUp")y-=20;if(event.key==="ArrowDown")y+=20;paint()});paint();
const stage=$("#stage"),unavailable=$("#stageUnavailable");stage.value="production";function switchStage(){const active=stage.value,available=active==="production"||active==="audit";$("#canvasHeaderTitle").textContent=active==="production"?"生产流程节点设置":active==="audit"?"审计流程节点设置":"阶段节点设置";document.querySelectorAll(".node").forEach((node)=>node.hidden=!available||node.dataset.stage!==active);unavailable.hidden=available}stage.onchange=switchStage;switchStage();
const modal=$("#modelSettingsModal"),closeModal=()=>modal.hidden=true;$("#openModelSettings").onclick=()=>{modal.hidden=false;$("#testConnection").focus()};$("#closeModelModal").onclick=closeModal;$("#cancelModelModal").onclick=closeModal;$("#applyModelModal").onclick=()=>{$("#modelSummary").textContent=$("#model").value||"未配置";closeModal()};
state.operator=stableOperator();try{const saved=JSON.parse(localStorage.getItem(contextKey)||"null");if(saved?.local_operator_id===state.operator)state.bookId=saved.current_book_id||null}catch{}load();
